Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using lab234.HelperSession;
using lab234.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace lab234.Controllers
{
    
    public class CartController : Controller
    {
        private readonly ProductData productData;

        public CartController(ProductData productData)
        {
            this.productData = productData;
        }

        //private readonly ProductModel productModel;
        //public CartController(ProductModel productModel)
        //{
        //    this.productModel = productModel;
        //}

        [Route("index")]
        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<ProductToCart>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.ProductModel.ProductPrice * item.Quantity);

            return View();
        }
        [Route("buy/{id}")]
        public IActionResult Buy(int id)
        {
            if (SessionHelper.GetObjectFromJson<List<ProductToCart>>(HttpContext.Session, "cart") == null)
            {
                List<ProductToCart> cart = new List<ProductToCart>(); cart.Add(new ProductToCart
                { ProductModel = productData.ProductList.FirstOrDefault(p => p.ProductId == id), Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<ProductToCart> cart = SessionHelper.GetObjectFromJson<List<ProductToCart>>(HttpContext.Session, "cart"); int index = isExist(id); if (index != -1) { cart[index].Quantity++; }

                else { cart.Add(new ProductToCart { ProductModel = productData.ProductList.FirstOrDefault(p => p.ProductId == id), Quantity = 1 }); }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");
        }
        [Route("remove/{id}")]
        public IActionResult Remove(int id)
        {
            List<ProductToCart> cart = SessionHelper.GetObjectFromJson<List<ProductToCart>>(HttpContext.Session, "cart");
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session,
           "cart", cart);
            return RedirectToAction("Index");
        }
        private int isExist(int id)
        {
            List<ProductToCart> cart = SessionHelper.GetObjectFromJson<List<ProductToCart>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].ProductModel.ProductId == id)
                {
                    return i;
                }
            }
            return -1;
        }
    }

}

Controllers/DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using lab234.Models;
using Microsoft.AspNetCore.Mvc;

namespace lab234.Controllers
{
    public class DetailController : Controller
    {
        private readonly ProductData productData;
        public DetailController(ProductData productData)
        {
            this.productData = productData;
        }
        [HttpGet("Detail/{id}/{name}")]
        public IActionResult Index(int id)
        {
            ProductModel productModel = productData.ProductList.FirstOrDefault(p => p.ProductId == id);
            return View(productModel);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using lab234.Models;

namespace lab234.Controllers
{
    public class HomeController : Controller
    {

        private ProductData data;
        public HomeController(ProductData productData)
        {
            data = productData;
        }
        public IActionResult Index()
        {
            return View(data.ProductList);
        }


        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@*@{
        ViewData["Title"] = "Home Page";
    }
    @model List<ProductModel>
    <<div class="row">
        @foreach (var item in Model)
        {
            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img src="~/images/@item.ProductImage" class="img-thumbnail" width="300px" height="300px" alt="iphoneX" />
                    <div class="card-body">
                        <h4 class="cardtitle">@item.ProductName</h4>
                        <p class="cardtext">@item.ProductPrice</p>
                    </div>
                    <div class="card-footer">
                        <a asp-controller="Detail"
                           asp-action="Index" asp-route-id="@item.ProductId" asp-route-name="@item.ProductName" class="btn btn-primary">Details</a>
                        <a href="#" class="btn btn-info">Buy now</a>
                    </div>
                </div>
            </div>
        }
    </div>*@


@{
    ViewData["Title"] = "Home Page";
}
@model List<ProductModel>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card h-100">
                <img class="card-img-top"
                     src="~/images/@item.ProductImage" alt="">
                <div class="card-body">
                    <h4 class="card-title">@item.ProductName</h4>
                    <p class="card-text">@item.Descriptions</p>
                </div>
                <div class="card-footer">
                    <a asp-controller="Detail" aspaction="Index" asp-route-id="@item.ProductId" asp-route-name="@item.ProductName" class="btn btn-primary">Details</a>

                    <a asp-controller="Cart" asp-action="Buy"
                       asp-route-id="@item.ProductId" class="btn btn-info">Buy now</a>
                </div>
            </div>
        </div>
    }
</div>
